name: data
on:
  schedule:
    - cron: 0 0 * * 3
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/content/dam/ircc/documents/json/data-ptime-en.json
          downloaded_filename: data-ptime-en.json
